name: Quality Gate

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv python install 3.13
      
      - name: Install & Test with Coverage
        run: |
          uv venv
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          uv pip install -e ".[dev]"
          uv run pytest --cov=src --cov-report=term-missing > coverage_report.txt
          
      - name: Prepare Coverage Artifacts
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.number }}" > pr_number.txt
          echo "<details><summary>ðŸš© Code Coverage Report</summary>" > coverage_comment.txt
          echo "\`\`\`" >> coverage_comment.txt
          cat coverage_report.txt >> coverage_comment.txt
          echo "\`\`\`" >> coverage_comment.txt
          echo "</details>" >> coverage_comment.txt

      - name: Upload Artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifact
          path: |
            pr_number.txt
            coverage_comment.txt